package caillou.company.clonemanager.background.bean.filter;

import caillou.company.clonemanager.background.bean.applicationFile.contract.ApplicationFile;
import java.util.HashSet;
import java.util.Set;

public class ArchiveExtensionFilter extends ExtensionFilter implements Filter<ApplicationFile> {
	
	public ArchiveExtensionFilter(){
		super();
		Set<String> extensions = new HashSet<>();
		extensions.add("a");
		extensions.add("ar");
		extensions.add("cpio");
		extensions.add("shar");
		extensions.add("LBR");
		extensions.add("iso");
		extensions.add("lbr");
		extensions.add("mar");
		extensions.add("tar");
		extensions.add("bz2");
                extensions.add("F");
                extensions.add("gz");
                extensions.add("lz");
                extensions.add("lzma");
                extensions.add("lzo");
                extensions.add("rz");
                extensions.add("sfark");
                extensions.add("xz");
                extensions.add("z");
                extensions.add("Z");
                extensions.add("infl");
                extensions.add("7z");
                extensions.add("s7z");
                extensions.add("ace");
                extensions.add("afa");
                extensions.add("alz");
                extensions.add("apk");
                extensions.add("arc");
                extensions.add("arj");
                extensions.add("b1");
                extensions.add("ba");
                extensions.add("bh");
                extensions.add("cab");
                extensions.add("cfs");
                extensions.add("cpt");
                extensions.add("dd");
                extensions.add("dgc");
                extensions.add("dmg");
                extensions.add("ear");
                extensions.add("gca");
                extensions.add("ha");
                extensions.add("hki");
                extensions.add("ice");
                extensions.add("jar");
                extensions.add("kgb");
                extensions.add("lzh");
                extensions.add("lha");
                extensions.add("lzx");
                extensions.add("pak");
                extensions.add("partimg");
                extensions.add("pea");
                extensions.add("pim");
                extensions.add("qda");
                extensions.add("rar");
                extensions.add("rk");
                extensions.add("sda");
                extensions.add("sea");
                extensions.add("sen");
                extensions.add("sfx");
                extensions.add("sit");
                extensions.add("sitx");
                extensions.add("sqx");
                extensions.add("tgz");
                extensions.add("tbz2");
                extensions.add("tlz");
                extensions.add("uc");
                extensions.add("uc0");
                extensions.add("uc2");
                extensions.add("ucn");
                extensions.add("ur2");
                extensions.add("ue2");
                extensions.add("uca");
                extensions.add("uha");
                extensions.add("war");
                extensions.add("wim");
                extensions.add("xar");
                extensions.add("xp3");
                extensions.add("yz1");
                extensions.add("zip");
                extensions.add("zipx");
                extensions.add("zoo");
                extensions.add("zpaq");
                extensions.add("zz");
                extensions.add("ecc");
                extensions.add("par");
                extensions.add("par2");                
		this.setExtensionsToKeep(extensions);
	}

}
